config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :students
  resources :lessons
  resources :enrollments do
    resources :memos, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_name,
    against: [:name],
    using: {
      tsearch: { prefix: true }
    }
  mount_uploader :photo, PhotoUploader
  has_many :enrollments
  has_many :lessons, through: :enrollments
  has_many :memos, through: :enrollments
  validates :name, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = policy_scope(Student)

    if params[:query].present?
      @students = Student.search_by_name(params[:query])
    else
      @students = Student.all
    end
  end

  def show
     authorize @student
  end

  def new
    @student = Student.new
    authorize @student
  end

  def create
    @student = Student.new(student_params)
    authorize @student
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  def edit
    authorize @student
  end

  def update
    @student.update(student_params)
    # @student = Student.update(student_params)
    authorize @student
      if @student.save
        redirect_to student_path(@student)
      else
        render :new
      end
  end

  def destroy
    @student.destroy
    authorize @student
    redirect_to students_path
  end

  private

  def find_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :birth_date, :category, :description, :photo)
  end
end

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<div class="student-new">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <div class="new-student-form">
      <div class="student-new-title text-center">
        <h2>Edit student</h2>
        <%= image_tag "student_hat.svg", class: "form-icon" %>
      </div>


      <div class="new-student-form-imput text-center">
        <%= simple_form_for @student do |form| %>
          <%= form.input :name %>
          <%= form.input :birth_date, as: :string, required: false, input_html: {class: "datepicker"}%>
          <%= form.input :category %>
          <%= form.input :description%>
          <%= form.input :photo %>
          <%= form.input :photo_cache, as: :hidden %>
          <%= form.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="mini-search">
  <section class="list-wrap">
    <div class="form-inline">
       <%= image_tag "student_hat.svg", class: "index-icon" %>
    </div>
  <input type="text" id="search-text" placeholder="search" class="search-box">
  <div class="list-count"></div>
  <ul id="list">
    <% @students.each do |student| %>
      <li class="in">
        <% if student.photo.blank?%>
          <%= image_tag "user.svg", class: "teachers-photos" %>
        <% else %>
          <%= cl_image_tag student.photo, crop: :fill, class: "teachers-photos"%>
        <% end %>
        <%= link_to student.name, student_path(student) %>
      </li>
    <% end %>
    <span class="empty-item">no results</span>
  </ul>
  </section>
</div>

app/views/students/new.html.erb
<div class="student-new">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
    <div class="form">
      <div class="form-title text-center">
        <h2>New student</h2>
        <%= image_tag "student_hat.svg", class: "form-icon" %>
      </div>
      <div class="form-imput text-center">
        <%= simple_form_for @student do |form| %>
          <%= form.input :name %>
          <%= form.input :birth_date, as: :string, required: false, input_html: {class: "datepicker"}%>
          <%= form.input :category %>
          <%= form.input :description%>
          <%= form.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="student-show">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="information-box">
      <div class="cover">
        <div class="show-information">
          <% if @student.photo.blank?%>
            <%= image_tag "student_hat.svg"%>
          <% else %>
            <%= cl_image_tag @student.photo, crop: :fill, width: "120" %>
          <% end %>
        </div>
      </div>

      <div class="main-student-page">
        <h1><%= @student.name %></h1>
        <h6><%= @student.birth_date.strftime("%B %e %Y") %></h6>
        <h6><%= @student.category %></h6>

        <div class = "student-lessons" >
          <h3><%= @student.name.split(" ").first %>'s lessons</h3>
            <div class = "student-lessons-list">
              <% student_lessons = @student.lessons.all.sort %>
              <% student_lessons.each do |l| %>
                <div class="student-lesson-card">
                  <%= link_to lesson_path(l) do %>
                    <div class = "student-lesson-card-information">
                      <div class="lesson-card-day">
                        <strong>
                          <%= l.start_time.strftime("%b %d") %>
                        </strong>
                      </div>
                      <div class="lesson-card-time">
                        <%= l.start_time.strftime("%H:%M") %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
        </div>

        </div>

        <div class="student-memo">
          <h3>Memo from teachers</h3>
          <div class="student-memo-list">
            <% if @student.memos.empty? %>
              <p>No memo available yet</p>
            <% else %>
              <% @student.memos.each do |memo| %>


                <div class="student-memo-card">
                  <p class="text-center level-<%= memo.enrollment.lesson.course.level.downcase%>" style="color: white"><strong>
                      <%= memo.enrollment.lesson.course.language %> - <%= memo.enrollment.lesson.course.level %>
                    </strong></p>
                  <div class="memo-card-content">
                    <div class="memo-item-picture">
                      <%= link_to user_path(memo.enrollment.lesson.user) do %>
                        <%= cl_image_tag memo.enrollment.lesson.user.photo, crop: :fill, class: "memo-teacher-pic"%>
                      <% end %>
                    </div>

                   <!--  <div class="student-memo-details text-center level-<%= memo.enrollment.lesson.course.level.downcase%>"> -->
                    <div class="student-memo-details text-center>">
                      <p><%= memo.comment %></p>
                    </div>

                    <div class="memo-item-date">
                      <%= memo.created_at.strftime("%b %d, %Y") %>
                    </div>
                  </div>

                </div>


              <% end %>
            <% end %>
          </div>
        </div>

          <ul class= "text-center">
          <% if current_user.role == "manager" %>
            <li class="change-photo">
              <%= simple_form_for @student, html: {class: "users-show-alignment"} do |f| %>
                <%= f.error_notification %>
                <div style="text-align: center">
                  <%= f.input :photo, label: 'Profile picture'%>
                  <%= f.input :photo_cache, as: :hidden%>
                </div>
                <%= f.button :submit, "save", class: 'btn btn-warning save-button margin-alignment'  %>
              <% end %>
            </li>
            <li class="margin-alignment">
              <%= link_to "delete the student account", cancel_user_registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %>
            </li>
          <% end %>
          </ul>
        </div>
        <div class="social">
      </div>
    </div>
  </div>
</div>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>