config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :students
  resources :lessons
  resources :enrollments do
    resources :memos, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" id="fixed-bar" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %> navbar-fixed-top" id="navbar">
  <!-- Logo -->
  <% if user_signed_in? %>
    <%= link_to lessons_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "newlogo.png" %>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "newlogo.png" %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <div class="navbar-bottons navbar-wagon-item">
        <ul class="list-inline">
          <% if current_user.role == "manager"%>
            <li class="after-icon teaching">
              <%= link_to new_lesson_path do %>
                <%= image_tag "teaching.svg", class: "avatar" %>
              <% end %>
            </li>
          <% end %>
          <li class="after-icon id-card">
            <%= link_to users_path do %>
              <%= image_tag "id_card.svg", class: " avatar" %>
            <% end %>
          </li>
          <li class="after-icon student-hat">
            <%= link_to students_path do %>
              <%= image_tag "student_hat.svg", class: " avatar" %>
            <% end %>
          </li>
        </ul>
      </div>
      <!-- Avatar with dropdown menu -->
      <div class="dropdown profile-border">

        <% if current_user.photo.blank? %>
          <%= image_tag "user.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li style= "text-align: center" >
            <%=current_user.first_name%>
          </li>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <div class="form-inputs form-signin navbar-form">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
          <%= f.text_field :email,
            class: "form-control",
            placeholder: "email"%>
          <%= f.password_field :password,
            class: "form-control",
            placeholder: "password"%>
          <%= f.submit 'Login', class: 'btn btn-primary'%>
        <% end %>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fas fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
              <i class="fas fa-id-card-alt"></i> <%= t(".teachers", default: "Teachers") %>
            <% end %>
          </li>
          <li>
            <%= link_to students_path do%>
              <i class="fas fa-graduation-cap"></i>  <%= t(".students", default: "Students") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>