config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :students
  resources :lessons
  resources :enrollments do
    resources :memos, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  belongs_to :user
  belongs_to :room
  has_many :enrollments, dependent: :destroy
  has_many :students, through: :enrollments
  has_many :memos, through: :enrollments
  validates :start_time, presence: true, uniqueness: { scope: :room_id }
  validates :start_time, presence: true, uniqueness: { scope: :user_id }

  def add_students(student_ids)
    student_ids.each do |id|
      Enrollment.create(lesson: self, student_id: id)
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :find_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = policy_scope(Lesson)
    @rooms = Room.all
    @user = current_user
  end

  def show
    authorize @lesson
    # @enrollments = @lesson.enrollments
    @memo = Memo.new

    # Passing the instance variable of the enrollment and new memo
  end

  def new
    if params[:room_id]
      @lesson = Lesson.new(room_id: params[:room_id], start_time: params[:start_time])
      authorize @lesson
    else
      @lesson = Lesson.new
      authorize @lesson
    end
  end

  def create
    if params[:recurring_check][:recurring]
      @lesson = Lesson.new(lesson_params)
      authorize @lesson
      if @lesson.save
        @lesson.add_students(params[:students]) if params[:students]
        start_time = @lesson.start_time
        (params[:recurring_check][:weeks].to_i-1).times do
          start_time = start_time + 7.days
          new_lesson = Lesson.new(lesson_params)
          new_lesson.start_time = start_time
          authorize new_lesson
          new_lesson.save
        end
        redirect_to lesson_path(@lesson)
      else
        render :new
      end
    else
      @lesson = Lesson.new(lesson_params)
      authorize @lesson
      if @lesson.save
        @lesson.add_students(params[:students]) if params[:students]
        redirect_to lesson_path(@lesson)
      else
        # render :new, start_time: params[:start_time], room_id: params[:room_id]
        render :new
      end
    end
  end

  def edit
    authorize @lesson
  end

  def update
    @lesson.update(lesson_params)
    authorize @lesson
    if @lesson.save
      @lesson.add_students(params[:students]) if params[:students]
      redirect_to lesson_path(@lesson)
    else
      render :new
    end
  end

  def destroy
    @lesson.destroy
    authorize @lesson
    redirect_to lessons_path
  end

  private

  def find_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:start_time, :user_id, :course_id, :room_id, :students, :comment)
  end
end

app/views/lessons/_daily_manager.html.erb
<div class="tab-pane" id="daily_view">
  <%= calendar number_of_days:1, events: @lessons do |date, lessons| %>
  <span class="date-str"><%= date %></span>
<div class = "room">
<table>
  <tr>
    <th>&nbsp;</th>
  </tr>
    <% (10..20).each do |h|%>
  <tr>
    <td><div class = "lesson-hour"><%= h %></div></td>
  </th>
    <% end %>
</table>
<% @rooms.each do |room| %>
<% vacant_cell = true %>
<table>
  <tr>
    <th>Room <%= room.name %></th>
  </tr>
  <% (10..20).each do |h|%>
    <% lessons.each do |lesson| %>
      <% if room.id == lesson.room.id && h==lesson.start_time.strftime('%H').to_i %>
        <% vacant_cell = false %>
        <tr><td>
          <%= link_to lesson_path(lesson) do %>
          <div class = "lesson-card level-<%= lesson.course.level.downcase %>">
            <%= lesson.start_time.strftime('%H') %> <%= lesson.start_time.strftime('%M') %>
<!--             <%= lesson.course.language %> -->
            <%= lesson.course.level %>
          </div>
          <% end %>
        </td></tr>
      <% end %>
    <% end %>
  <% if vacant_cell %>
    <tr>
      <td>
        <%= link_to new_lesson_path(room_id: room.id, start_time: DateTime.new(date.year, date.month, date.day, h)) do %>
          <div class = "lesson-card-vacant">XXXXXXXXXXXXXXXX</div>
        <% end %>
      </td>
    </tr>
  <% end %>
  <% vacant_cell = true %>
  <% end %>
</table>
<% end %>
<% end %>
</div>

app/views/lessons/_daily_teacher.html.erb
<div class="user-show">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-sm-offset-3">
    <div class="information-box">

      <div class="cover">
        <div class="show-information">
          <% if current_user.photo.blank?%>
            <%= image_tag "user.svg"%>
          <% else %>
            <%= cl_image_tag current_user.photo, crop: :fill, width: "120" %>
          <% end %>
        </div>
      </div>
      <div class="main username-mobile">
        <h1><%= @user.first_name %>  <%= @user.last_name %></h1>
      </div>

<div class="teachers-calender">
  <%= calendar number_of_days:1, events: @lessons do |date, lessons| %>
    <table>
      <% vacant_cell = true %>
      <% (10..20).each do |h|%>
        <% lessons.each do |lesson| %>
          <% if h==lesson.start_time.strftime('%H').to_i %>
            <% vacant_cell = false %>
            <tr>
              <td>
                <div class = "lesson-hour">
                  <%= h %>
                </div>
              </td>
              <td>
              <%= link_to lesson_path(lesson) do %>
                <div class = "lesson-card mobile-view level-<%= lesson.course.level.downcase %>">
                  <div class="lesson-room">
                    Room: <%= lesson.room.name %>
                  </div>
                  <div class="lesson-level">
                    <%= lesson.course.level %>
                  </div>
                  <div class="number-of-student">
                    <% if lesson.students.count >= 4 %>
                      <%= image_tag "student_hat.svg" , class: "small-icon", style: "border-radius: 50%"%> x <%= lesson.students.count
                       %>
                      <% else %>
                      <% lesson.students.each do |student| %>
                        <%= cl_image_tag student.photo.url, class: "small-icon", style: "border-radius: 50%"%>
                      <% end %>
                    <% end %>

                  </div>
                </div>
              <% end %>
            </td></tr>
          <% end %>
        <% end %>


      <% if vacant_cell %>
        <tr>
          <td><div class = "lesson-hour"><%= h %></div></td>
          <td>
              <div class = "lesson-card-vacant">XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</div>
            <% end %>
          </td>
        </tr>
        <% vacant_cell = true %>
      <% end %>
    </table>
  <% end %>
</div>

    </div>
  </div>
</div>

app/views/lessons/_weekly.html.erb
<div class="weekly-calender">
  <%= week_calendar events: @lessons do |date, lessons| %>
    <span class="date-str"><%= date %></span>
    <div class = "room">
      <table>
        <tr>
          <th>&nbsp;</th>
        </tr>
        </tr>
          <% (10..20).each do |h|%>
        <tr>
          <td><div class = "lesson-hour"><%= h %></div></td>
        </th>
          <% end %>
      </table>
      <% @rooms.each do |room| %>
      <% vacant_cell = true %>
      <table>
        <tr>
          <th>Room <%= room.name %></th>
        </tr>
        <% (10..20).each do |h|%>
          <% lessons.each do |lesson| %>
            <% if room.id == lesson.room.id && h==lesson.start_time.strftime('%H').to_i %>
              <% vacant_cell = false %>
              <tr><td>
                <%= link_to lesson_path(lesson) do %>

                  <div class = "lesson-card card-level-<%= lesson.course.level.downcase %>">
                    <div class= "lesson-time">
                      <%= lesson.start_time.strftime('%H:%M') %>
                    </div>
                    <div class="lesson-photo">
                    <%=cl_image_tag lesson.user.photo, class: "small-icon", style: "border-radius: 50%"%>
                    </div>
                  </div>
                <% end %>
              </td></tr>
            <% end %>
          <% end %>
        <% if vacant_cell %>
          <tr>
            <td>
              <%= link_to new_lesson_path(room_id: room.id, start_time: DateTime.new(date.year, date.month, date.day, h)) do %>
                <div class = "lesson-card-vacant">XXXXXXXXXXXXXX</div>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% vacant_cell = true %>
        <% end %>
      </table>
    <% end %>
  <% end %>
</div>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/destroy.html.erb
<h1>Lessons#destroy</h1>
<p>Find me in app/views/lessons/destroy.html.erb</p>

app/views/lessons/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <h1>Edit lessons</h1>
      <%= simple_form_for @lesson, html: { class: "time-picker"} do |form| %>
        <%= simple_form_for :lesson, method: "get" do |f| %>
          <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>

          <%= form.association :course, collection: Course.order('level'), label_method: :course_name,  prompt: "Choose a course"
   %>
          <%= form.association :room, collection: Room.order('name'), label_method: :name,  prompt: "Choose a room"
   %>
          <%= form.association :user, collection: User.order('first_name'), label_method: :first_name,  prompt: "Choose a Teacher"
   %>
           <label for="id_label_multiple">
          Students <br>
          <%= select_tag "students", options_from_collection_for_select(
                Student.all, :id, :name),
                class: 'select2 js-example-basic-multiple js-states form-control', id: "id_label_multiple", name: "students[]", multiple: "multiple" %>
        </label>
          <%= form.button :submit %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/lessons/index.html.erb
<div class = "lesson-index" style = "padding: 20px">
  <% if @user.role == "manager"%>
    <%= render 'weekly' %>
  <% else %>
    <%= render 'daily_teacher' %>
  <% end %>
</div>

app/views/lessons/new.html.erb
<div class="lesson-new">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-sm-offset-3">
    <div class="form">
      <div class="form-title text-center">
        <h2>New lesson</h2>
        <%= image_tag "teaching.svg", class: "index-icon" %>
      </div>
      <div class="form-imput">
        <%= simple_form_for @lesson, html: { class: "time-picker"} do |form| %>
          <% if @lesson.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @lesson.errors.full_messages.each do |message| %>
                  <li style="color:red;"><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <% if @lesson.start_time.present? %>
            <%= form.datetime_select :start_time, required: false %>
          <% else %>
            <%= form.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
          <% end %>
          <%= form.association :room, collection: Room.order('name'), label_method: :name,  prompt: "Choose a room" %>
          <%= form.association :course, collection: Course.order('level'), label_method: :level,  prompt: "Choose a course" %>
          <%#= form.association :user, label: :Teacher, collection: User.order('first_name'), label_method: :first_name,  prompt: "Choose a Teacher" %>
          <div id="teachers-select2" class="form-group lesson-select">
            <label for="id_label_multiple2">
              Teachers <br>
              <%= select_tag "teachers", options_from_collection_for_select(
                    User.all, :id, :first_name),
                    class: 'select2 js-example-basic-multiple js-states form-control students-width', id: "id_label_multiple2", name: "lesson[user_id]", multiple: "multiple" %>
            </label>
          </div>
          <div id="students" class="form-group lesson-select">
            <label for="id_label_multiple">
              Students <br>
              <%= select_tag "students", options_from_collection_for_select(
                    Student.all, :id, :name),
                    class: 'select2 js-example-basic-multiple js-states form-control students-width', id: "id_label_multiple", name: "students[]", multiple: "multiple" %>
            </label>
          </div>
            <div class="form-group lesson-recurring">
            <%= simple_fields_for :recurring_check do |n| %>
            <%= n.input :recurring, as: :boolean, checked_value: true, unchecked_value: false %><p>for</p>
            <%= n.select :weeks, (2..13) %> <p>weeks</p>
            <% end %>
            </div>
          <%= form.button :submit, class: "btn btn-primary button green-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="information-box">
      <div class="show-title text-center">
        <h2>
          <%= @lesson.start_time.strftime("%A %B %e %Y ") %>
        </h2>
        <div class="lesson-info">
          <div class="lesson-details">
            <%= image_tag "time.svg"%><span style="padding-right: 15px;"><%= @lesson.start_time.strftime("%l:%M %p") %></span>
          </div>
          <div class="lesson-details">
            <%= image_tag "sand-clock.svg" %><span><%= @lesson.course.duration %>mins</span>
          </div>

        </div>
      </div>

      <div class="teacher-information text-center">
        <div class="user-photo">
          <%= link_to user_path(@lesson.user) do%>
            <% if @lesson.user.photo.blank?%>
              <%= image_tag "user.svg", class: "user-photo-information" %>
            <% else %>
              <%= cl_image_tag @lesson.user.photo, crop: :fill, class: "teacher-photo-information"%>
            <% end %>
          <% end %>
        </div>
        <div class="teacher-name text-center">
          <h3>
            <%= @lesson.user.first_name %>  <%= @lesson.user.last_name %>
          </h3>
        </div>
      </div>

      <div class="lesson-level text-center level-<%= @lesson.course.level.downcase %>">
        <p style="padding: 2px 0;">
          <%= @lesson.course.level %> - <%= @lesson.course.language %>
        </p>
      </div>
      <div class="students">
        <h4><%= @lesson.user.first_name %>'s students</h4>
        <% @lesson.enrollments.each do |enrollment| %>
          <div class="student">
            <div class="student-photo">
              <%= link_to student_path(enrollment.student) do %>
              <%= cl_image_tag enrollment.student.photo, class: "user-photo-information" %>
              <% end %>
            </div>
            <div class="student-comment">
            <div class="student-name">
              <strong><p><%= enrollment.student.name %></p></strong>
            </div>
              <% if enrollment.memos.count.zero? %>
                <%= simple_form_for [enrollment, @memo], html: {class: "form-structure"} do |f| %>
                  <div class="input-target">
                    <%= f.input :comment, placeholder: "Leave a memo for this class", label: false %>
                  </div>
                  <div class="svg-background">
                  <%= f.button :button do%>
                    <%= image_tag "share-option.svg", class: "small-icon write-memo-icon " %>
                  <% end %>
                </div>
                <% end %>
              <% else %>
                <% enrollment.memos.each do |memo| %>
                  <%= memo.comment %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="bottom">
          <ul class="list-inline icon-line">
            <li>
              <%= link_to edit_lesson_path(@lesson) do %>
            <!-- nozomi didn't get to design nice, please someone do -->
              <% end %>
            </li>
            <li>
                <%= link_to lesson_path(@lesson), method: :delete, data: { confirm: "Are you sure you want to DELETE the lesson?" } do %>
                  <%= image_tag "trash.svg", class: "small-icon small-icon-effect form-trash", alt: "Delete this lesson" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>